type TranslationValue = string | string[] | { [key: string]: TranslationValue };

type Translations = {
  [key: string]: TranslationValue;
};

export const LOCALES = ['en', 'es', 'pt', 'fr', 'de', 'it', 'ar'] as const;
export type Locale = (typeof LOCALES)[number];
export const RTL_LOCALES: Locale[] = ['ar'];
export const DEFAULT_LOCALE: Locale = 'en';

export function isRTL(locale: string): boolean {
  return RTL_LOCALES.includes(locale as Locale);
}

// Helper to avoid writing empty stubs for every language
function sameAsEn(): Translations {
  return {} as Translations;
}

const en: Translations = {
  nav: { home: 'Home', free: 'Free Signals', premium: 'Premium', trackRecord: 'Track Record', pricing: 'Pricing', login: 'Login', signup: 'Sign Up', account: 'My Account', logout: 'Logout', blog: 'Blog' },
  home: { title: 'NOIRAX', subtitle: 'Autonomous Crypto Trading Signal System', terminalIntro: '> Multi-coin technical + fundamental analysis system started', terminalAwaiting: '> Awaiting market data...', latestSignals: 'Latest Signals', ctaPremium: 'Unlock Premium', ctaFree: 'View Free Signals', disclaimer: 'Educational and informational content. Not financial advice.', typingText: 'Analyzing 100+ pairs with technical + fundamental data' },
  free: { title: 'Free Signals', subtitle: 'Real-time signals for the top 15 cryptocurrencies', delayWarning: 'Free signals cover the top 15 coins by market cap with conservative targets.', exchangeDisclaimer: 'Trade on recommended exchanges. These signals are educational.', noSignals: 'No signals available at this time.', refreshIn: 'Refresh in' },
  premium: { title: 'Premium Signals', subtitle: 'Full universe, optimized targets, advanced analysis', upgradePrompt: 'Unlock the full potential with NOIRAX Premium', upgradeButton: 'View Plans', filters: 'Filters', allCoins: 'All coins', confidence: 'Min confidence', timeframe: 'Timeframe', positionCalculator: 'Position Calculator', capital: 'Capital ($)', riskPercent: 'Risk (%)', positionSize: 'Position Size', riskLevel: 'Risk Level', low: 'Low', medium: 'Medium', high: 'High', riskLevelLowDesc: 'Low volatility (ATR under ~3% of the price): contained moves, tighter stop-loss.', riskLevelMediumDesc: 'Medium volatility (ATR around 3-5% of the price): wider swings.', riskLevelHighDesc: 'High volatility (ATR over ~5% of the price): wide swings, larger stop-loss. Not a lower-quality signal — just a more volatile coin.' },
  trackRecord: { title: 'Track Record', subtitle: 'Complete signal history. Unfiltered, transparent results.', winRate: 'Win Rate', totalSignals: 'Total Signals', wins: 'Wins', losses: 'Losses', pending: 'Pending', noData: 'No historical data available.' },
  legal: { title: 'Legal Notice', disclaimer: 'NOIRAX is an educational and informational platform about cryptocurrency technical analysis. Nothing on this site constitutes financial advice, investment recommendation, or solicitation to buy or sell assets. Cryptocurrency trading carries a high risk of financial loss. We do not guarantee any profitability. Past results are not indicative of future results. Consult a certified financial advisor before making investment decisions.', riskWarning: 'RISK WARNING: Cryptocurrency trading can result in total loss of your invested capital. Only trade with money you can afford to lose.', spainWarning: 'NOIRAX is not a registered investment advisor. This content is for educational purposes only and does not constitute investment advice regulated by any financial authority, including the CNMV (Spain) or SEC (USA).' },
  auth: { loginTitle: 'Login', signupTitle: 'Create Account', email: 'Email', password: 'Password', loginButton: 'Login', signupButton: 'Sign Up', magicLink: 'Send Magic Link', noAccount: "Don't have an account?", hasAccount: 'Already have an account?', error: 'Authentication error', success: 'Operation successful', checkEmail: 'Check your email for the login link.', googleLogin: 'Continue with Google', googleSignup: 'Continue with Google', orContinue: 'or' },
  pricing: { title: 'Pricing', free: { name: 'Free', price: 'Free', description: 'Real-time signals for top coins', features: ['Top 15 crypto signals', 'Real-time updates', 'Conservative TP/SL targets', 'Technical + fundamental analysis', 'Public access'] }, premium: { name: 'Premium', price: '€7.99/mo', description: 'Full universe with optimized targets', features: ['Full coin universe (50+)', 'Optimized TP1/TP2/TP3 ladder', 'Extended risk/reward targets', 'Position calculator', 'Advanced track record filters', 'Priority AI explanations', 'Fundamental signal tags'], cta: 'Subscribe' }, annual: { name: 'Annual Premium', price: '€79/yr', description: 'Save 2 months', features: ['Everything in Premium', '2 months free'], cta: 'Subscribe' } },
  common: { loading: 'Loading...', error: 'Error', retry: 'Retry', close: 'Close', learnMore: 'Learn More', subscribe: 'Subscribe', comingSoon: 'Coming Soon', language: 'Language', readMore: 'Read More', backToHome: 'Back to Home', shareSignal: 'Share Signal' },
  duration: { all: 'All', scalping: 'Scalping', scalpingDesc: 'Quick trades, minutes to hours', swing: 'Swing', swingDesc: 'Medium-term, days', long: 'Position', longDesc: 'Long-term, weeks' },
  premiumPrompt: { title: 'Premium Signal', description: 'This is a premium signal. Subscribe to view the full analysis.', cta: 'View Premium Plans', later: 'Not now' },
  disclaimerBanner: { text: 'Educational content. Not financial advice. Trading involves risk of loss.' },
  blog: { title: 'NOIRAX Blog', subtitle: 'Educational content about technical analysis and crypto trading.', readMore: 'Read More', noPosts: 'No posts yet.', related: 'Related Articles' },
  signal: { buySignal: 'BUY Signal', sellSignal: 'SELL Signal', entryZone: 'Entry Zone', stopLoss: 'Stop Loss', takeProfit: 'Take Profit', riskReward: 'Risk/Reward', indicators: 'Indicators Used', verified: 'Verified', pending: 'Pending', generated: 'Generated', learnMoreAbout: 'Learn more about', learnAboutRsi: 'Learn more about RSI', learnAboutMacd: 'Learn more about MACD', whyThisSignal: 'Why this signal?', viewOnTrackRecord: 'View in Track Record', share: 'Share Signal', confidenceLabel: 'Confluence', confidenceTooltip: 'Agreement between technical indicators, not a probability of success', chartNote: 'Market chart by TradingView — visualization only. NOIRAX analysis comes from Bybit/OKX market data, not from this chart.', explanationFallback: 'Technical and fundamental market analysis based on recent price action.', chartUnavailable: 'Chart not available for this coin — it is not listed on any supported exchange.' },
  cookies: { text: 'This site uses cookies for essential functionality only. No tracking cookies are used without your consent.', accept: 'Accept', reject: 'Reject', moreInfo: 'Privacy Policy' },
  trading: {
    nav: 'Auto Trading', title: 'Auto Trading', subtitle: 'Connect your exchange and let NOIRAX trade for you — you stay in control.',
    howItWorksTitle: 'How it works', howIt1: 'You connect your exchange with an API key (trading only, no withdrawal access).', howIt2: 'You choose how it operates: fully automatic, or with your confirmation before each trade.', howIt3: 'You pick a risk profile. The system respects hard safety limits you cannot exceed.', howIt4: 'You set your own daily loss brake. When it triggers, trading pauses until you restart it.',
    selectExchange: 'Step 1 — Choose your exchange', searchExchange: 'Search exchanges...', searchNoResults: 'No exchanges match your search.', noAccount: "Don't have an account on", createHere: 'Create one here', docs: 'API docs', securityGuide: 'Security guide',
    stepGuide: 'Step 2 — Create your API key safely', guideIntro: 'Before pasting anything, create the key on the exchange with these settings:', guideTradingOnly: 'Enable ONLY the trading permission (spot and/or futures).', guideNoWithdraw: 'NEVER enable the withdrawal permission — NOIRAX does not need it and never will.', guideIpWhitelist: 'If the exchange offers an IP whitelist, activate it (recommended).', guidePassphrase: 'If the exchange requires a passphrase (e.g. OKX), keep it at hand — you will need it in the next step.', guideNeverShare: 'Your keys stay encrypted on our servers. We never show them back to you, not even to you.', guideBack: 'Back to exchange list', guideContinue: 'I created my key — continue',
    configure: 'Configure', noAccountShort: "I DON'T have an account yet", noAccountDesc: 'Register on {exchange} first (2 minutes), then create your API key.', haveAccountShort: 'I ALREADY have an account', haveAccountDesc: 'Open the API key page on {exchange} and create a key with trading permission only, without withdrawal access.', generateApiKey: 'Generate my API key',
    stepCredentials: 'Step 6 — Connect your keys', getKeysTitle: "Don't have an account or API keys on {exchange} yet?", getKeysReminder: 'Create the API keys on the exchange first (2 minutes): trading permission only, no withdrawal access. Open the exchange page in a new tab, create your keys, and paste them below when you have them.', commissionPricing: 'Commission: {rate}% only on WINNING trades, calculated on net profit: (exit price - entry price) x quantity - exchange fees. Losing or neutral trades cost nothing. No fixed fee, no subscription.', apiKey: 'API Key', apiSecret: 'API Secret', passphrase: 'Passphrase (required for OKX)', credentialsHelp: 'Paste your API Key and Secret here. They are encrypted with AES-256-GCM before being stored, and only the last 4 characters of the key are kept visible for identification.',
    stepMode: 'Step 2 — How should it operate?', modeAuto: 'Automatic', modeAutoDesc: 'NOIRAX executes the signals directly, without asking you.', modeConfirm: 'With my confirmation', modeConfirmDesc: 'Each signal becomes a pending order that you approve manually. If you do not approve within 15 minutes, the signal expires.', modeExpiryNote: 'Pending orders expire if not approved within 15 minutes.',
    stepProfile: 'Step 3 — Your risk profile', profileIntro: 'A risk profile controls how much of your capital is used per trade and how many trades can be open at once. You can change it later.', profileValues: 'Position per trade: {pos}% · Max open trades: {max} · Daily loss brake: {loss}%',
    profile: { conservative: 'Conservative', conservativeDesc: 'Small positions, few trades, maximum protection.', moderate: 'Moderate', moderateDesc: 'Balanced risk for steady operation.', aggressive: 'Aggressive', aggressiveDesc: 'Larger positions and more open trades.', smallFrequent: 'Small & frequent', smallFrequentDesc: 'Small risk per trade with a higher number of trades. Lower risk per operation, higher frequency.' },
    advanced: 'Advanced (custom)', advancedDesc: 'Set each value yourself, always within the system safety limits.', positionPct: 'Position size (% of capital)', dailyLoss: 'Daily loss brake (%)', maxPositions: 'Max simultaneous trades', advancedCapsNote: 'System limits you cannot exceed: {pos}% per trade, {loss}% daily loss, {max} trades.',
    stepBrake: 'Step 4 — Your daily loss brake', brakeIntro: 'This is your emergency stop. If your account loses this percentage in one day, trading pauses automatically until you restart it manually. You cannot disable it: choose a value between 1% and 15%.',
    stepLegal: 'Step 5 — Risk notice (required)', legalAccept: 'I have read and accept the risk notice above.', legalTitle: 'Risk Notice and Conditions for Auto Trading',
    legalS1: '1. REAL RISK OF CAPITAL LOSS. Trading cryptoassets carries a high and real risk of partial or total loss of the invested capital. I can lose money, including the entire amount invested. NOIRAX does not guarantee profits on any trade.',
    legalS2: '2. PAST RESULTS. NOIRAX historical signal results, published statistics or any past performance do not guarantee or imply future results. Markets can behave unpredictably.',
    legalS3: '3. NO CUSTODY OF FUNDS. NOIRAX does not manage, custody, own or have access to my funds at any time. The API keys I connect are used exclusively to execute trading orders on my account, with trading-only permissions (spot/futures depending on the exchange) and WITHOUT withdrawal permission. Under no circumstances can my keys withdraw, transfer or move funds out of the exchange. I keep control and custody of my assets at all times. NOIRAX recommends enabling the IP whitelist and never enabling the withdrawal permission when creating the key.',
    legalS4: '4. COMMISSION CALCULATION. For each trade executed automatically on my behalf that results in positive net profit, NOIRAX charges 25% of the net profit. Net profit is calculated as: (exit price - entry price) x quantity - fees and charges applied by the exchange itself. Exchange fees are deducted before calculating the percentage. If the net result is zero or negative (a loss), NOIRAX charges no commission. There is no fixed fee or subscription for this service.',
    legalS5: '5. COMMISSION RATE CHANGES. The percentage may be adjusted in the future. NOIRAX will communicate any change at least 15 calendar days in advance by email and through a notice on this page. The change will apply to both new connections and already active ones once the notice period has elapsed. Each trade records the rate in effect at the time of execution.',
    legalS6: '6. USER RESPONSIBILITY. Orders are executed automatically according to the parameters I have configured (risk profile, operating mode and limits). I am ultimately responsible for the trades made on my account, for periodically reviewing my connections and for keeping my keys and settings up to date.',
    legalS7: '7. NOIRAX LIABILITY LIMITATION. NOIRAX will make its best effort to keep the service working correctly, but does not guarantee uninterrupted availability or absence of errors. To the maximum extent permitted by law, NOIRAX is not liable for damages arising from its own technical failures (software errors, service outages, orders executed by mistake, delays or loss of connectivity with the exchange) or from the consequences of such failures on my trades. This limitation is separate from my responsibility for normal operation described in point 6.',
    legalS8: '8. NOT ADVICE. This page does not constitute financial, investment, tax or legal advice. I must consult a qualified financial or tax advisor before trading.',
    legalS9: '9. DECLARATION. I declare that I have read, understood and accept the above conditions, and that I am aware that automated trading involves a real risk of capital loss.',
    connectButton: 'Connect securely', connecting: 'Connecting...', connectError: 'Could not connect. Check the fields and try again.', validationError: 'Warning: {error}', connected: 'Connected', connectAnother: 'Connect another exchange',
    dashboard: { title: 'Your auto trading', status: 'Status', active: 'Active', paused: 'Paused', pausedReason: 'Why it paused: {reason}', mode: 'Mode', profile: 'Profile', perTrade: 'Position per trade', dailyBrake: 'Daily loss brake', maxTrades: 'Max open trades', keyHint: 'Key ending in', emergency: 'EMERGENCY STOP', resume: 'Resume trading', pause: 'Pause trading', disconnected: 'Disconnected', disconnect: 'Disconnect', settings: 'Settings', saveSettings: 'Save changes', activeTrades: 'Active trades', noActiveTrades: 'No active trades yet. Automated execution activates in a future phase — here you will see your open trades.', history: 'History', noHistory: 'No completed trades yet.', executionSoon: 'Order execution will be activated in the next phase. Your connection, limits and settings are already saved securely.', commission: 'Commission: {rate}% only on winning trades, calculated on net profit after the exchange fees. Never on losing trades. No fixed fee.', validationNote: 'Validation note: {note}', engineActive: 'Execution engine: ACTIVE. New signals are executed automatically (or shown here for your approval), always with stop-loss and take-profit attached. Your limits and daily brake are enforced automatically.', pendingTitle: 'Waiting for your approval', approve: 'Approve and execute', decline: 'Decline', expiresIn: 'Expires in', openTitle: 'Open trades', unrealized: 'Unrealized PnL', currentPrice: 'Current price', historyTitle: 'Closed trades', pnl: 'Net PnL', closedAt: 'Closed', noPending: 'No signals waiting for approval right now.', chartsTitle: 'Your results at a glance', capitalEvolution: 'Accumulated PnL over time (USDT) — every closed trade, in order.', winRateLabel: 'Win rate — share of closed trades that made money.', netPnlLabel: 'Net PnL, all time — profits minus losses, minus exchange fees.', commissionTotalLabel: 'Commission paid to NOIRAX (25% of net profit on winning trades only).', distributionTitle: 'How your results are distributed (return per closed trade)', byCoinTitle: 'Results by coin', byProfileTitle: 'Results by risk profile', byModeTitle: 'Results by mode (automatic vs with confirmation)', refresh: 'Refresh', sl: 'Stop loss', tp: 'Take profit', pending: 'pending', expiredTrade: 'expired', cancelledTrade: 'cancelled', failedTrade: 'failed', tradeOpen: 'open' },
    paper: { title: 'Try it with simulated money', badge: 'PAPER MODE - simulated money', banner: 'You are in trial mode: 10,000 simulated USDT. No real money is used.', ctaDesc: 'No exchange account? No keys needed. Practice with 10,000 simulated USDT using the exact same engine, limits and protections.', start: 'Start paper trading', balance: 'Simulated balance: 10,000 USDT (fictitious)', disclaimer: 'Simulated results do not guarantee real results.', trialResult: 'How you would have done (trial)', tradesCount: 'Trades', simBalance: 'Simulated balance now', trialEnded: 'Your 7-day trial period has ended. You can keep practicing or connect a real exchange.' }, oneClick: { button: 'Trade with one click', title: 'Trade with one click -', notional: 'Position value', risk: 'Risk per trade', note: 'This order is placed with stop-loss and take-profit attached. It respects your profile limits, daily brake and max open trades.', confirm: 'Confirm and execute', done: 'Order placed successfully. Follow it in the trading dashboard.', connectPrompt: 'Connect your exchange to trade with one click' },
    backToExchange: 'Back to exchanges', finish: 'Finish', done: 'All set', doneText: 'Your connection has been saved securely. You can manage it anytime from this page.',
    testnetLabel: 'Testnet mode (sandbox, no real money)', testnetDesc: 'Connect to the exchange sandbox environment instead of the live market. Use this to try the system safely. Order placement, SL/TP and the full cycle work exactly the same.', testnetBadge: 'TESTNET',
  },
  privacy: { title: 'Privacy Policy', dataController: 'Data Controller', dataControllerText: 'NOIRAX (operated by NoiraMaster). Contact: aissaeljarrarielfahli@gmail.com', dataCollected: 'Data Collected', dataEmail: 'Email address (for account creation and login)', dataPayment: 'Payment information', dataPaymentNote: 'NOIRAX does not store or process credit card details. All payments are handled securely by Stripe.', dataLanguage: 'Language preference (stored locally in your browser)', dataCookies: 'Cookie consent preference (stored locally in your browser)', purpose: 'Purpose of Data Processing', purposeText: 'To provide trading signal accounts, process premium subscriptions, and improve the service. We do not sell or share personal data with third parties.', retention: 'Data Retention', retentionText: 'Account data is retained until you request deletion. Payment records are retained as required by tax law (typically 5 years).', rgpd: 'Your GDPR Rights', rgpdText: 'You have the right to access, rectify, or delete your personal data at any time by contacting us. You may also export your data or withdraw consent for processing.', contact: 'Contact', contactText: 'For any privacy-related inquiries: aissaeljarrarielfahli@gmail.com' },
};

const es: Translations = {
  nav: { home: 'Inicio', free: 'Señales Free', premium: 'Premium', trackRecord: 'Track Record', pricing: 'Planes', login: 'Iniciar Sesión', signup: 'Registrarse', account: 'Mi Cuenta', logout: 'Cerrar Sesión', blog: 'Blog' },
  home: { title: 'NOIRAX', subtitle: 'Sistema Autónomo de Señales de Trading Cripto', terminalIntro: '> Sistema de análisis técnico + fundamental multi-moneda iniciado', terminalAwaiting: '> Esperando datos de mercado...', latestSignals: 'Últimas Señales', ctaPremium: 'Desbloquear Premium', ctaFree: 'Ver Señales Free', disclaimer: 'Contenido educativo e informativo. No es asesoría financiera.', typingText: 'Analizando 100+ pares con datos técnicos + fundamentales' },
  free: { title: 'Señales Free', subtitle: 'Señales en tiempo real para las principales criptomonedas', delayWarning: 'Las señales free cubren las 15 principales monedas por market cap con objetivos conservadores.', exchangeDisclaimer: 'Opera en exchanges recomendados. Estas señales son educativas.', noSignals: 'No hay señales disponibles en este momento.', refreshIn: 'Actualización en' },
  premium: { title: 'Señales Premium', subtitle: 'Universo completo, objetivos optimizados, análisis avanzado', upgradePrompt: 'Desbloquea todo el potencial con NOIRAX Premium', upgradeButton: 'Ver Planes', filters: 'Filtros', allCoins: 'Todas las monedas', confidence: 'Confianza mínima', timeframe: 'Timeframe', positionCalculator: 'Calculadora de Posición', capital: 'Capital ($)', riskPercent: 'Riesgo (%)', positionSize: 'Tamaño de posición', riskLevel: 'Nivel de Riesgo', low: 'Bajo', medium: 'Medio', high: 'Alto', riskLevelLowDesc: 'Volatilidad baja (ATR por debajo de ~3% del precio): movimientos contenidos, stop-loss más ajustado.', riskLevelMediumDesc: 'Volatilidad media (ATR en torno al 3-5% del precio): oscilaciones más amplias.', riskLevelHighDesc: 'Volatilidad alta (ATR por encima de ~5% del precio): oscilaciones amplias, stop-loss más amplio. No es una señal de peor calidad — solo una moneda más volátil.' },
  trackRecord: { title: 'Track Record', subtitle: 'Histórico completo de señales. Sin filtros, sin ocultar resultados.', winRate: 'Win Rate', totalSignals: 'Total Señales', wins: 'Aciertos', losses: 'Fallos', pending: 'Pendientes', noData: 'No hay datos históricos disponibles.' },
  legal: { title: 'Aviso Legal', disclaimer: 'NOIRAX es una plataforma de contenido educativo e informativo sobre análisis técnico de criptomonedas. Nada en este sitio constituye asesoría financiera, recomendación de inversión o solicitud para comprar o vender activos. El trading de criptomonedas conlleva un alto riesgo de pérdida financiera. No garantizamos rentabilidad alguna. Los resultados pasados no son indicativos de resultados futuros. Consulte a un asesor financiero certificado antes de tomar decisiones de inversión.', riskWarning: 'ADVERTENCIA DE RIESGO: El trading de criptomonedas puede resultar en la pérdida total de su capital invertido. Solo opere con dinero que pueda permitirse perder.', spainWarning: 'NOIRAX no es un servicio de asesoramiento de inversión regulado por la CNMV. Este contenido es exclusivamente educativo/informativo. El usuario opera bajo su propia responsabilidad. Consulte a un asesor financiero certificado antes de tomar decisiones de inversión.' },
  auth: { loginTitle: 'Iniciar Sesión', signupTitle: 'Crear Cuenta', email: 'Correo electrónico', password: 'Contraseña', loginButton: 'Iniciar Sesión', signupButton: 'Registrarse', magicLink: 'Enviar Magic Link', noAccount: '¿No tienes cuenta?', hasAccount: '¿Ya tienes cuenta?', error: 'Error de autenticación', success: 'Operación exitosa', checkEmail: 'Revisa tu correo para el enlace de acceso.', googleLogin: 'Continuar con Google', googleSignup: 'Continuar con Google', orContinue: 'o' },
  pricing: { title: 'Planes', free: { name: 'Free', price: 'Gratis', description: 'Señales en tiempo real para las principales monedas', features: ['Señales top 15 criptomonedas', 'Actualizaciones en tiempo real', 'Objetivos TP/SL conservadores', 'Análisis técnico + fundamental', 'Acceso público'] }, premium: { name: 'Premium', price: '7,99€/mes', description: 'Universo completo con objetivos optimizados', features: ['Universo completo (50+ monedas)', 'Escalera TP1/TP2/TP3 optimizada', 'Objetivos risk/reward extendidos', 'Calculadora de posición', 'Filtros avanzados de track record', 'Explicaciones IA prioritarias', 'Tags de señales fundamentales'], cta: 'Suscribirse' }, annual: { name: 'Premium Anual', price: '79€/año', description: 'Ahorra 2 meses', features: ['Todo lo de Premium', '2 meses gratis'], cta: 'Suscribirse' } },
  common: { loading: 'Cargando...', error: 'Error', retry: 'Reintentar', close: 'Cerrar', learnMore: 'Más información', subscribe: 'Suscribirse', comingSoon: 'Próximamente', language: 'Idioma', readMore: 'Leer más', backToHome: 'Volver al Inicio', shareSignal: 'Compartir Señal' },
  duration: { all: 'Todas', scalping: 'Scalping', scalpingDesc: 'Operaciones rápidas, minutos a horas', swing: 'Swing', swingDesc: 'Medio plazo, días', long: 'Posición', longDesc: 'Largo plazo, semanas' },
  premiumPrompt: { title: 'Señal Premium', description: 'Esta es una señal premium. Suscríbete para ver el análisis completo.', cta: 'Ver Planes Premium', later: 'Ahora no' },
  disclaimerBanner: { text: 'Contenido educativo. No es asesoría financiera. El trading conlleva riesgo de pérdida.' },
  blog: { title: 'Blog NOIRAX', subtitle: 'Contenido educativo sobre análisis técnico y trading cripto.', readMore: 'Leer más', noPosts: 'Aún no hay artículos.', related: 'Artículos Relacionados' },
  signal: { buySignal: 'Señal de COMPRA', sellSignal: 'Señal de VENTA', entryZone: 'Zona de Entrada', stopLoss: 'Stop Loss', takeProfit: 'Take Profit', riskReward: 'Risk/Reward', indicators: 'Indicadores Usados', verified: 'Verificado', pending: 'Pendiente', generated: 'Generado', learnMoreAbout: 'Más información sobre', learnAboutRsi: 'Más información sobre RSI', learnAboutMacd: 'Más información sobre MACD', whyThisSignal: '¿Por qué esta señal?', viewOnTrackRecord: 'Ver en Track Record', share: 'Compartir Señal', confidenceLabel: 'Confluencia', confidenceTooltip: 'Acuerdo entre indicadores técnicos, no es una probabilidad de éxito', chartNote: 'Gráfico de mercado por TradingView — solo visualización. El análisis de NOIRAX proviene de datos de Bybit/OKX, no de este gráfico.', explanationFallback: 'Análisis técnico y fundamental del mercado basado en la acción reciente del precio.', chartUnavailable: 'Gráfico no disponible para esta moneda — no está listada en ningún exchange compatible.' },
  cookies: { text: 'Este sitio utiliza cookies solo para funcionalidad esencial. No se utilizan cookies de seguimiento sin tu consentimiento.', accept: 'Aceptar', reject: 'Rechazar', moreInfo: 'Política de Privacidad' },
  trading: {
    nav: 'Trading Auto', title: 'Trading Auto', subtitle: 'Conecta tu exchange y deja que NOIRAX opere por ti — tú mantienes el control.',
    howItWorksTitle: 'Cómo funciona', howIt1: 'Conectas tu exchange con una API key (solo trading, sin acceso a retiros).', howIt2: 'Eliges cómo opera: totalmente automático, o con tu confirmación antes de cada operación.', howIt3: 'Eliges un perfil de riesgo. El sistema respeta límites de seguridad que no puedes superar.', howIt4: 'Configuras tu propio freno de pérdida diaria. Si se activa, el trading se pausa hasta que lo reactives.',
    selectExchange: 'Paso 1 — Elige tu exchange', searchExchange: 'Buscar exchange...', searchNoResults: 'Ningún exchange coincide con tu búsqueda.', noAccount: '¿No tienes cuenta en', createHere: 'Créala aquí', docs: 'Docs API', securityGuide: 'Guía de seguridad',
    stepGuide: 'Paso 2 — Crea tu API key con seguridad', guideIntro: 'Antes de pegar nada, crea la clave en el exchange con estos ajustes:', guideTradingOnly: 'Activa SOLO el permiso de trading (spot y/o futures).', guideNoWithdraw: 'NO actives nunca el permiso de retiro (withdraw) — NOIRAX no lo necesita ni lo necesitará.', guideIpWhitelist: 'Si el exchange ofrece lista blanca de IPs, actívala (recomendado).', guidePassphrase: 'Si el exchange exige passphrase (p.ej. OKX), tenla a mano — la necesitarás en el siguiente paso.', guideNeverShare: 'Tus claves quedan cifradas en nuestros servidores. Nunca te las mostramos de vuelta, ni a ti.', guideBack: 'Volver a la lista de exchanges', guideContinue: 'Ya he creado mi clave — continuar',
    configure: 'Configurar', noAccountShort: 'NO tengo cuenta todavía', noAccountDesc: 'Regístrate primero en {exchange} (2 minutos) y luego crea tu API key.', haveAccountShort: 'YA tengo cuenta', haveAccountDesc: 'Abre la página de API keys de {exchange} y crea una clave con permiso solo de trading, sin acceso a retiros.', generateApiKey: 'Generar mi API key',
    stepCredentials: 'Paso 6 — Conecta tus claves', getKeysTitle: '¿Aún no tienes cuenta o API keys en {exchange}?', getKeysReminder: 'Crea primero las API keys en el exchange (2 minutos): permiso solo de trading, sin acceso a retiros. Abre la página del exchange en una pestaña nueva, crea tus claves y pégalas abajo cuando las tengas.', commissionPricing: 'Comisión: {rate}% solo sobre operaciones GANADORAS, calculada sobre el beneficio neto: (precio de salida − precio de entrada) × cantidad − comisiones del exchange. Si la operación es perdedora o neutra, no se cobra nada. Sin cuota fija ni suscripción.', apiKey: 'API Key', apiSecret: 'API Secret', passphrase: 'Passphrase (obligatoria en OKX)', credentialsHelp: 'Pega aquí tu API Key y Secret. Se cifran con AES-256-GCM antes de guardarse, y solo se conservan visibles los últimos 4 caracteres de la clave para identificarla.',
    stepMode: 'Paso 2 — ¿Cómo debe operar?', modeAuto: 'Automático', modeAutoDesc: 'NOIRAX ejecuta las señales directamente, sin preguntarte.', modeConfirm: 'Con mi confirmación', modeConfirmDesc: 'Cada señal se convierte en una orden pendiente que apruebas manualmente. Si no la apruebas en 15 minutos, la señal expira.', modeExpiryNote: 'Las órdenes pendientes expiran si no se aprueban en 15 minutos.',
    stepProfile: 'Paso 3 — Tu perfil de riesgo', profileIntro: 'Un perfil de riesgo controla cuánto capital se usa por operación y cuántas operaciones pueden estar abiertas a la vez. Puedes cambiarlo después.', profileValues: 'Posición por operación: {pos}% · Máx. operaciones abiertas: {max} · Freno diario: {loss}%',
    profile: { conservative: 'Conservador', conservativeDesc: 'Posiciones pequeñas, pocas operaciones, máxima protección.', moderate: 'Moderado', moderateDesc: 'Riesgo equilibrado para operar con constancia.', aggressive: 'Agresivo', aggressiveDesc: 'Posiciones más grandes y más operaciones abiertas.', smallFrequent: 'Pequeñas y frecuentes', smallFrequentDesc: 'Riesgo pequeño por operación con un mayor número de operaciones. Menor riesgo por operación, mayor frecuencia.' },
    advanced: 'Avanzado (personalizado)', advancedDesc: 'Configura cada valor tú mismo, siempre dentro de los límites de seguridad del sistema.', positionPct: 'Tamaño de posición (% del capital)', dailyLoss: 'Freno de pérdida diaria (%)', maxPositions: 'Máx. operaciones simultáneas', advancedCapsNote: 'Límites del sistema que no puedes superar: {pos}% por operación, {loss}% de pérdida diaria, {max} operaciones.',
    stepBrake: 'Paso 4 — Tu freno de pérdida diaria', brakeIntro: 'Este es tu freno de emergencia. Si tu cuenta pierde este porcentaje en un día, el trading se pausa automáticamente hasta que lo reactives manualmente. No puedes desactivarlo: elige un valor entre 1% y 15%.',
    stepLegal: 'Paso 5 — Aviso de riesgo (obligatorio)', legalAccept: 'He leído y acepto el aviso de riesgo anterior.', legalTitle: 'Aviso de Riesgo y Condiciones del Trading Automático',
    legalS1: '1. RIESGO REAL DE PÉRDIDA DE CAPITAL. El trading de criptoactivos conlleva un riesgo elevado y real de pérdida parcial o total del capital invertido. Puedo perder dinero, incluida la totalidad del importe invertido. NOIRAX no garantiza beneficios en ninguna operación.',
    legalS2: '2. RESULTADOS PASADOS. Los resultados históricos de las señales, estadísticas publicadas o cualquier rendimiento pasado de NOIRAX no garantizan ni implican resultados futuros. Los mercados pueden comportarse de forma imprevisible.',
    legalS3: '3. NO CUSTODIA DE FONDOS. NOIRAX no gestiona, custodia, posee ni tiene acceso a mis fondos en ningún momento. Las claves API que conecto se usan exclusivamente para la ejecución de órdenes de trading en mi cuenta, con permisos únicamente de trading (spot/futures según el exchange) y sin permiso de retiro. En ningún caso mis claves permiten retirar, transferir o mover fondos fuera del exchange. Mantengo el control y la custodia de mis activos en todo momento. NOIRAX recomienda activar la lista blanca de IPs y no habilitar nunca el permiso de retiro al crear la clave.',
    legalS4: '4. CÁLCULO DE LA COMISIÓN. Por cada operación ejecutada automáticamente en mi nombre que resulte en beneficio neto positivo, NOIRAX cobra el 25% del beneficio neto. El beneficio neto se calcula así: (precio de salida − precio de entrada) × cantidad − comisiones y tasas aplicadas por el propio exchange. Las comisiones del exchange se deducen antes de calcular el porcentaje. Si el resultado neto es cero o negativo (pérdida), NOIRAX no cobra comisión alguna. No existe cuota fija ni suscripción por este servicio.',
    legalS5: '5. CAMBIOS EN EL PORCENTAJE DE COMISIÓN. El porcentaje puede ajustarse en el futuro. NOIRAX comunicará cualquier cambio con al menos 15 días naturales de antelación por correo electrónico y mediante aviso en esta página. El cambio se aplicará tanto a conexiones nuevas como a conexiones ya activas, una vez transcurrido el plazo de antelación. En cada operación quedará registrado el porcentaje vigente en el momento de su ejecución.',
    legalS6: '6. RESPONSABILIDAD DEL USUARIO. Las órdenes se ejecutan automáticamente según los parámetros que yo haya configurado (perfil de riesgo, modo de operación y límites). Soy responsable final de las operaciones realizadas en mi cuenta, de la revisión periódica de mis conexiones y de mantener mis claves y ajustes actualizados.',
    legalS7: '7. LIMITACIÓN DE RESPONSABILIDAD DE NOIRAX. NOIRAX pondrá su mejor esfuerzo para que el servicio funcione correctamente, pero no garantiza disponibilidad ininterrumpida ni ausencia de errores. En la medida máxima permitida por la ley, NOIRAX no será responsable de daños derivados de fallos técnicos propios (errores de software, caídas del servicio, órdenes ejecutadas por error, retrasos o pérdidas de conectividad con el exchange) ni de las consecuencias de dichos fallos en mis operaciones. Esta limitación es independiente de mi responsabilidad sobre el funcionamiento normal descrita en el punto 6.',
    legalS8: '8. NO ES ASESORAMIENTO. Esta página no constituye asesoramiento financiero, de inversión, fiscal ni legal. Debo consultar con un asesor financiero o fiscal cualificado antes de operar.',
    legalS9: '9. DECLARACIÓN. Declaro que he leído, comprendo y acepto las condiciones anteriores, y que soy consciente de que el trading automático implica un riesgo real de pérdida de capital.',
    connectButton: 'Conectar de forma segura', connecting: 'Conectando...', connectError: 'No se pudo conectar. Revisa los campos e inténtalo de nuevo.', validationError: 'Aviso: {error}', connected: 'Conectado', connectAnother: 'Conectar otro exchange',
    dashboard: { title: 'Tu trading automático', status: 'Estado', active: 'Activo', paused: 'Pausado', pausedReason: 'Motivo de la pausa: {reason}', mode: 'Modo', profile: 'Perfil', perTrade: 'Posición por operación', dailyBrake: 'Freno de pérdida diaria', maxTrades: 'Máx. operaciones abiertas', keyHint: 'Clave terminada en', emergency: 'STOP DE EMERGENCIA', resume: 'Reanudar trading', pause: 'Pausar trading', disconnected: 'Desconectado', disconnect: 'Desconectar', settings: 'Ajustes', saveSettings: 'Guardar cambios', activeTrades: 'Operaciones activas', noActiveTrades: 'Aún no hay operaciones activas. La ejecución automática se activa en una fase futura — aquí verás tus operaciones abiertas.', history: 'Historial', noHistory: 'Aún no hay operaciones cerradas.', executionSoon: 'La ejecución de órdenes se activará en la próxima fase. Tu conexión, límites y ajustes ya están guardados de forma segura.', commission: 'Comisión: {rate}% solo sobre operaciones ganadoras, calculada sobre el beneficio neto tras las comisiones del exchange. Nunca sobre operaciones perdedoras. Sin cuota fija.', validationNote: 'Nota de validación: {note}', engineActive: 'Motor de ejecución: ACTIVO. Las nuevas señales se ejecutan automáticamente (o aparecen aquí para tu aprobación), siempre con stop-loss y take-profit adjuntos. Tus límites y freno diario se aplican automáticamente.', pendingTitle: 'Esperando tu aprobación', approve: 'Aprobar y ejecutar', decline: 'Rechazar', expiresIn: 'Expira en', openTitle: 'Operaciones abiertas', unrealized: 'PnL no realizado', currentPrice: 'Precio actual', historyTitle: 'Operaciones cerradas', pnl: 'PnL neto', closedAt: 'Cerrada', noPending: 'No hay señales esperando tu aprobación ahora mismo.', chartsTitle: 'Tus resultados de un vistazo', capitalEvolution: 'PnL acumulado en el tiempo (USDT) — cada operación cerrada, en orden.', winRateLabel: 'Ratio de aciertos — porcentaje de operaciones cerradas que dieron beneficio.', netPnlLabel: 'PnL neto total — beneficios menos pérdidas, menos comisiones del exchange.', commissionTotalLabel: 'Comisión pagada a NOIRAX (25% del beneficio neto solo en operaciones ganadoras).', distributionTitle: 'Cómo se distribuyen tus resultados (rentabilidad por operación cerrada)', byCoinTitle: 'Resultados por moneda', byProfileTitle: 'Resultados por perfil de riesgo', byModeTitle: 'Resultados por modo (automático vs con confirmación)', refresh: 'Actualizar', sl: 'Stop loss', tp: 'Take profit', pending: 'pendiente', expiredTrade: 'expirada', cancelledTrade: 'cancelada', failedTrade: 'fallida', tradeOpen: 'abierta' },
    paper: { title: 'Prueba con dinero simulado', badge: 'MODO PRUEBA - dinero simulado', banner: 'Estás en modo prueba: 10,000 USDT simulados. No se usa dinero real.', ctaDesc: '¿Sin cuenta en ningún exchange? No necesitas claves. Practica con 10,000 USDT simulados usando el mismo motor, límites y protecciones.', start: 'Empezar modo prueba', balance: 'Saldo simulado: 10,000 USDT (ficticio)', disclaimer: 'Los resultados simulados no garantizan resultados reales.', trialResult: 'Así te habría ido (prueba)', tradesCount: 'Operaciones', simBalance: 'Saldo simulado actual', trialEnded: 'Tu periodo de prueba de 7 días ha terminado. Puedes seguir practicando o conectar un exchange real.' },     oneClick: { button: 'Operar con un clic', title: 'Operar con un clic -', notional: 'Valor de la posición', risk: 'Riesgo por operación', note: 'Esta orden se coloca con stop-loss y take-profit adjuntos. Respeta los límites de tu perfil, el freno diario y el máximo de operaciones.', confirm: 'Confirmar y ejecutar', done: 'Orden colocada correctamente. Síguela en el panel de trading.', connectPrompt: 'Conecta tu exchange para operar con un clic' },
    backToExchange: 'Volver a exchanges', finish: 'Finalizar', done: '¡Todo listo!', doneText: 'Tu conexión se ha guardado de forma segura. Puedes gestionarla cuando quieras desde esta página.',
    testnetLabel: 'Modo testnet (sandbox, sin dinero real)', testnetDesc: 'Conecta al entorno de pruebas del exchange en lugar del mercado real. Úsalo para probar el sistema de forma segura. La colocación de órdenes, SL/TP y el ciclo completo funcionan exactamente igual.', testnetBadge: 'TESTNET',
  },
  privacy: { title: 'Política de Privacidad', dataController: 'Responsable del Tratamiento', dataControllerText: 'NOIRAX (operado por NoiraMaster). Contacto: aissaeljarrarielfahli@gmail.com', dataCollected: 'Datos Recogidos', dataEmail: 'Dirección de correo electrónico (para creación de cuenta e inicio de sesión)', dataPayment: 'Información de pago', dataPaymentNote: 'NOIRAX no almacena ni procesa datos de tarjetas de crédito. Todos los pagos son gestionados de forma segura por Stripe.', dataLanguage: 'Preferencia de idioma (almacenada localmente en tu navegador)', dataCookies: 'Preferencia de consentimiento de cookies (almacenada localmente)', purpose: 'Finalidad del Tratamiento', purposeText: 'Proporcionar cuentas de señales de trading, procesar suscripciones premium y mejorar el servicio. No vendemos ni compartimos datos personales con terceros.', retention: 'Conservación de Datos', retentionText: 'Los datos de cuenta se conservan hasta que solicites su eliminación. Los registros de pago se conservan según lo requerido por la ley fiscal (generalmente 5 años).', rgpd: 'Tus Derechos RGPD', rgpdText: 'Tienes derecho a acceder, rectificar o eliminar tus datos personales en cualquier momento contactándonos. También puedes exportar tus datos o retirar el consentimiento.', contact: 'Contacto', contactText: 'Para cualquier consulta relacionada con la privacidad: aissaeljarrarielfahli@gmail.com' },
};

const pt: Translations = {
  nav: { home: 'Início', free: 'Sinais Free', premium: 'Premium', trackRecord: 'Histórico', pricing: 'Planos', login: 'Entrar', signup: 'Cadastrar', account: 'Minha Conta', logout: 'Sair', blog: 'Blog' },
  home: { title: 'NOIRAX', subtitle: 'Sistema Autônomo de Sinais de Trading Cripto', terminalIntro: '> Sistema de análise técnica multi-moeda iniciado', terminalAwaiting: '> Aguardando dados de mercado...', latestSignals: 'Últimos Sinais', ctaPremium: 'Desbloquear Premium', ctaFree: 'Ver Sinais Free', disclaimer: 'Conteúdo educativo e informativo. Não é aconselhamento financeiro.', typingText: 'Analisando mais de 100 pares em tempo real' },
  legal: { title: 'Aviso Legal', disclaimer: 'NOIRAX é uma plataforma de conteúdo educativo e informativo sobre análise técnica de criptomoedas. Nada neste site constitui aconselhamento financeiro. O trading de criptomoedas envolve alto risco de perda financeira. Não garantimos rentabilidade. Resultados passados não são indicativos de resultados futuros.', riskWarning: 'AVISO DE RISCO: Trading de criptomoedas pode resultar em perda total do capital investido.', spainWarning: 'Aviso: Verifique a legalidade do trading de cripto no seu país. Este conteúdo é educativo.' },
  pricing: { title: 'Planos', free: { name: 'Free', price: 'Grátis', description: 'Sinais em tempo real para principais moedas', features: ['Top 15 criptomoedas', 'Atualizações em tempo real', 'Objetivos TP/SL conservadores', 'Análise técnica + fundamental', 'Acesso público'] }, premium: { name: 'Premium', price: '€7,99/mês', description: 'Universo completo com objetivos otimizados', features: ['Universo completo (50+ moedas)', 'Escada TP1/TP2/TP3 otimizada', 'Objetivos risk/reward estendidos', 'Calculadora de posição', 'Filtros avançados de histórico', 'Explicações IA prioritárias', 'Tags de sinais fundamentais'], cta: 'Assinar' }, annual: { name: 'Premium Anual', price: '€79/ano', description: 'Economize 2 meses', features: ['Tudo do Premium', '2 meses grátis'], cta: 'Assinar' } },
  signal: { buySignal: 'Sinal de COMPRA', sellSignal: 'Sinal de VENDA', entryZone: 'Zona de Entrada', stopLoss: 'Stop Loss', takeProfit: 'Take Profit', riskReward: 'Risco/Retorno', indicators: 'Indicadores', verified: 'Verificado', pending: 'Pendente', generated: 'Gerado', confidenceLabel: 'Confluência', confidenceTooltip: 'Acordo entre indicadores técnicos, não é uma probabilidade de sucesso' },
  cookies: { text: 'Este site utiliza cookies apenas para funcionalidade essencial. Nenhum cookie de rastreamento é usado sem seu consentimento.', accept: 'Aceitar', reject: 'Rejeitar', moreInfo: 'Política de Privacidade' },
  privacy: { title: 'Política de Privacidade', dataController: 'Controlador de Dados', dataControllerText: 'NOIRAX (operado por NoiraMaster). Contato: aissaeljarrarielfahli@gmail.com', dataCollected: 'Dados Coletados', dataEmail: 'Endereço de email (para criação de conta e login)', dataPayment: 'Informação de pagamento', dataPaymentNote: 'NOIRAX não armazena nem processa dados de cartão de crédito. Todos os pagamentos são processados de forma segura pela Stripe.', dataLanguage: 'Preferência de idioma (armazenada localmente no seu navegador)', dataCookies: 'Preferência de consentimento de cookies (armazenada localmente)', purpose: 'Finalidade do Tratamento', purposeText: 'Fornecer contas de sinais de trading, processar assinaturas premium e melhorar o serviço. Não vendemos nem compartilhamos dados pessoais com terceiros.', retention: 'Retenção de Dados', retentionText: 'Os dados da conta são retidos até que você solicite a exclusão. Os registros de pagamento são retidos conforme exigido pela lei fiscal (geralmente 5 anos).', rgpd: 'Seus Direitos RGPD', rgpdText: 'Você tem o direito de acessar, retificar ou excluir seus dados pessoais a qualquer momento entrando em contato conosco.', contact: 'Contato', contactText: 'Para consultas relacionadas à privacidade: aissaeljarrarielfahli@gmail.com' },
  common: { loading: 'Carregando...', error: 'Erro', retry: 'Tentar novamente', close: 'Fechar', learnMore: 'Saiba mais', subscribe: 'Assinar', language: 'Idioma' },
  disclaimerBanner: { text: 'Conteúdo educativo. Não é aconselhamento financeiro. Trading envolve risco.' },
  free: { title: 'Sinais Free', subtitle: 'Sinais em tempo real para as principais criptomoedas', delayWarning: 'Sinais free cobrem as 15 principais moedas por market cap com objetivos conservadores.', exchangeDisclaimer: 'Estes sinais são educativos.', noSignals: 'Nenhum sinal disponível.', refreshIn: 'Atualizar em' },
  premium: { title: 'Sinais Premium', subtitle: 'Universo completo, objetivos otimizados, análise avançada', upgradePrompt: 'Desbloqueie todo o potencial', upgradeButton: 'Ver Planos', filters: 'Filtros', allCoins: 'Todas moedas', confidence: 'Confiança min', timeframe: 'Timeframe', positionCalculator: 'Calculadora', capital: 'Capital ($)', riskPercent: 'Risco (%)', positionSize: 'Tamanho', riskLevel: 'Nível de Risco', low: 'Baixo', medium: 'Médio', high: 'Alto' },
  trackRecord: { title: 'Histórico', subtitle: 'Histórico completo de sinais.', winRate: 'Win Rate', totalSignals: 'Total Sinais', wins: 'Acertos', losses: 'Erros', pending: 'Pendentes', noData: 'Sem dados disponíveis.' },
  auth: { loginTitle: 'Entrar', signupTitle: 'Criar Conta', email: 'Email', password: 'Senha', loginButton: 'Entrar', signupButton: 'Cadastrar', magicLink: 'Enviar Magic Link', noAccount: 'Não tem conta?', hasAccount: 'Já tem conta?', error: 'Erro de autenticação', success: 'Operação concluída', checkEmail: 'Verifique seu email.', googleLogin: 'Continuar com Google', googleSignup: 'Continuar com Google', orContinue: 'ou' },
  premiumPrompt: { title: 'Sinal Premium', description: 'Assine para ver análise completa.', cta: 'Ver Planos', later: 'Agora não' },
  blog: { title: 'Blog NOIRAX', subtitle: 'Conteúdo educativo sobre análise técnica.', readMore: 'Ler mais', noPosts: 'Sem artigos ainda.', related: 'Artigos Relacionados' },
};

const fr: Translations = {
  nav: { home: 'Accueil', free: 'Signaux Gratuits', premium: 'Premium', trackRecord: 'Historique', pricing: 'Tarifs', login: 'Connexion', signup: "S'inscrire", account: 'Mon Compte', logout: 'Déconnexion', blog: 'Blog' },
  home: { title: 'NOIRAX', subtitle: 'Système Autonome de Signaux de Trading Crypto', terminalIntro: '> Système d\'analyse technique multi-monnaie démarré', terminalAwaiting: '> Attente des données marché...', latestSignals: 'Derniers Signaux', ctaPremium: 'Débloquer Premium', ctaFree: 'Voir Signaux Gratuits', disclaimer: 'Contenu éducatif et informatif. Pas de conseil financier.', typingText: 'Analyse de 100+ paires en temps réel' },
  legal: { title: 'Mentions Légales', disclaimer: 'NOIRAX est une plateforme éducative sur l\'analyse technique crypto. Rien sur ce site ne constitue un conseil financier. Le trading de crypto comporte un risque élevé de perte.', riskWarning: 'AVERTISSEMENT : Le trading de crypto peut entraîner une perte totale du capital investi.', spainWarning: 'Avis : Vérifiez la légalité du trading crypto dans votre pays. Contenu éducatif uniquement.' },
  pricing: { title: 'Tarifs', free: { name: 'Gratuit', price: 'Gratuit', description: 'Signaux en temps réel pour les principales cryptos', features: ['Top 15 cryptos', 'Mises à jour temps réel', 'Objectifs TP/SL conservateurs', 'Analyse technique + fondamentale', 'Accès public'] }, premium: { name: 'Premium', price: '7,99€/mois', description: 'Univers complet avec objectifs optimisés', features: ['Univers complet (50+ cryptos)', 'Échelle TP1/TP2/TP3 optimisée', 'Objectifs risk/reward étendus', 'Calculateur de position', 'Filtres historique avancés', 'Explications IA prioritaires', 'Tags signaux fondamentaux'], cta: 'S\'abonner' }, annual: { name: 'Premium Annuel', price: '79€/an', description: 'Économisez 2 mois', features: ['Tout le Premium', '2 mois gratuits'], cta: 'S\'abonner' } },
  signal: { buySignal: 'Signal ACHAT', sellSignal: 'Signal VENTE', entryZone: 'Zone d\'Entrée', stopLoss: 'Stop Loss', takeProfit: 'Take Profit', riskReward: 'Risque/Rendement', indicators: 'Indicateurs', verified: 'Vérifié', pending: 'En attente', generated: 'Généré', confidenceLabel: 'Confluence', confidenceTooltip: 'Accord entre indicateurs techniques, pas une probabilité de succès' },
  cookies: { text: 'Ce site utilise des cookies uniquement pour les fonctionnalités essentielles. Aucun cookie de suivi n\'est utilisé sans votre consentement.', accept: 'Accepter', reject: 'Refuser', moreInfo: 'Politique de Confidentialité' },
  privacy: { title: 'Politique de Confidentialité', dataController: 'Responsable du Traitement', dataControllerText: 'NOIRAX (exploité par NoiraMaster). Contact: aissaeljarrarielfahli@gmail.com', dataCollected: 'Données Collectées', dataEmail: 'Adresse e-mail (pour la création de compte et la connexion)', dataPayment: 'Informations de paiement', dataPaymentNote: 'NOIRAX ne stocke ni ne traite les données de carte de crédit. Tous les paiements sont traités en toute sécurité par Stripe.', dataLanguage: 'Préférence linguistique (stockée localement dans votre navigateur)', dataCookies: 'Préférence de consentement aux cookies (stockée localement)', purpose: 'Finalité du Traitement', purposeText: 'Fournir des comptes de signaux de trading, traiter les abonnements premium et améliorer le service. Nous ne vendons ni ne partageons les données personnelles avec des tiers.', retention: 'Conservation des Données', retentionText: 'Les données du compte sont conservées jusqu\'à ce que vous demandiez leur suppression. Les enregistrements de paiement sont conservés selon les exigences de la loi fiscale (généralement 5 ans).', rgpd: 'Vos Droits RGPD', rgpdText: 'Vous avez le droit d\'accéder, de rectifier ou de supprimer vos données personnelles à tout moment en nous contactant.', contact: 'Contact', contactText: 'Pour toute question relative à la confidentialité: aissaeljarrarielfahli@gmail.com' },
  common: { loading: 'Chargement...', error: 'Erreur', retry: 'Réessayer', close: 'Fermer', learnMore: 'En savoir plus', subscribe: 'S\'abonner', language: 'Langue' },
  disclaimerBanner: { text: 'Contenu éducatif. Pas un conseil financier. Le trading comporte des risques.' },
  free: { title: 'Signaux Gratuits', subtitle: 'Signaux en temps réel pour les principales cryptos', delayWarning: 'Les signaux gratuits couvrent les 15 principales cryptos avec des objectifs conservateurs.', exchangeDisclaimer: 'Ces signaux sont éducatifs.', noSignals: 'Aucun signal disponible.', refreshIn: 'Rafraîchir dans' },
  premium: { title: 'Signaux Premium', subtitle: 'Univers complet, objectifs optimisés, analyse avancée', upgradePrompt: 'Débloquez tout le potentiel', upgradeButton: 'Voir les Offres', filters: 'Filtres', allCoins: 'Toutes', confidence: 'Confiance min', timeframe: 'Timeframe', positionCalculator: 'Calculateur', capital: 'Capital ($)', riskPercent: 'Risque (%)', positionSize: 'Taille', riskLevel: 'Niveau de Risque', low: 'Faible', medium: 'Moyen', high: 'Élevé' },
  trackRecord: { title: 'Historique', subtitle: 'Historique complet des signaux.', winRate: 'Taux de Réussite', totalSignals: 'Total Signaux', wins: 'Gagnés', losses: 'Perdus', pending: 'En attente', noData: 'Aucune donnée disponible.' },
  auth: { loginTitle: 'Connexion', signupTitle: 'Créer un Compte', email: 'Email', password: 'Mot de passe', loginButton: 'Connexion', signupButton: "S'inscrire", magicLink: 'Envoyer Magic Link', noAccount: 'Pas de compte ?', hasAccount: 'Déjà un compte ?', error: 'Erreur d\'authentification', success: 'Opération réussie', checkEmail: 'Vérifiez votre email.', googleLogin: 'Continuer avec Google', googleSignup: 'Continuer avec Google', orContinue: 'ou' },
  premiumPrompt: { title: 'Signal Premium', description: 'Abonnez-vous pour voir l\'analyse complète.', cta: 'Voir les Offres', later: 'Plus tard' },
  blog: { title: 'Blog NOIRAX', subtitle: 'Contenu éducatif sur l\'analyse technique.', readMore: 'Lire plus', noPosts: 'Pas encore d\'articles.', related: 'Articles Similaires' },
};

const de: Translations = {
  nav: { home: 'Start', free: 'Kostenlose Signale', premium: 'Premium', trackRecord: 'Aufzeichnung', pricing: 'Preise', login: 'Anmelden', signup: 'Registrieren', account: 'Mein Konto', logout: 'Abmelden', blog: 'Blog' },
  home: { title: 'NOIRAX', subtitle: 'Autonomes Krypto-Trading-Signalsystem', terminalIntro: '> Multi-Coin technische Analyse gestartet', terminalAwaiting: '> Warte auf Marktdaten...', latestSignals: 'Letzte Signale', ctaPremium: 'Premium Freischalten', ctaFree: 'Kostenlose Signale', disclaimer: 'Bildungs- und Informationsinhalt. Keine Finanzberatung.', typingText: 'Analysiere 100+ Paare in Echtzeit' },
  legal: { title: 'Rechtlicher Hinweis', disclaimer: 'NOIRAX ist eine Bildungsplattform für Krypto-Analyse. Nichts auf dieser Seite stellt eine Finanzberatung dar. Krypto-Handel birgt hohes Verlustrisiko.', riskWarning: 'RISIKOWARNUNG: Krypto-Handel kann zum Totalverlust führen.', spainWarning: 'Hinweis: Prüfen Sie die Legalität von Krypto-Handel in Ihrem Land. Nur Bildungsinhalt.' },
  pricing: { title: 'Preise', free: { name: 'Kostenlos', price: 'Kostenlos', description: 'Echtzeit-Signale für Top-Kryptos', features: ['Top 15 Kryptos', 'Echtzeit-Updates', 'Konservative TP/SL-Ziele', 'Technische + fundamentale Analyse', 'Öffentlicher Zugang'] }, premium: { name: 'Premium', price: '7,99€/Monat', description: 'Volles Universum mit optimierten Zielen', features: ['Alle Coins (50+)', 'Optimierte TP1/TP2/TP3-Stufen', 'Erweiterte Risk/Reward-Ziele', 'Positionsrechner', 'Erweiterte Historien-Filter', 'Priorisierte KI-Analyse', 'Fundamentale Signal-Tags'], cta: 'Abonnieren' }, annual: { name: 'Jahres-Premium', price: '79€/Jahr', description: '2 Monate sparen', features: ['Alles Premium', '2 Monate gratis'], cta: 'Abonnieren' } },
  signal: { buySignal: 'KAUF-Signal', sellSignal: 'VERKAUF-Signal', entryZone: 'Eintrittszone', stopLoss: 'Stop Loss', takeProfit: 'Take Profit', riskReward: 'Risiko/Ertrag', indicators: 'Indikatoren', verified: 'Verifiziert', pending: 'Ausstehend', generated: 'Generiert', confidenceLabel: 'Konfluenz', confidenceTooltip: 'Übereinstimmung technischer Indikatoren, keine Erfolgswahrscheinlichkeit' },
  cookies: { text: 'Diese Website verwendet Cookies nur für essentielle Funktionen. Ohne Ihre Zustimmung werden keine Tracking-Cookies verwendet.', accept: 'Akzeptieren', reject: 'Ablehnen', moreInfo: 'Datenschutzerklärung' },
  privacy: { title: 'Datenschutzerklärung', dataController: 'Verantwortlicher', dataControllerText: 'NOIRAX (betrieben von NoiraMaster). Kontakt: aissaeljarrarielfahli@gmail.com', dataCollected: 'Erhobene Daten', dataEmail: 'E-Mail-Adresse (für Kontoeinrichtung und Anmeldung)', dataPayment: 'Zahlungsinformationen', dataPaymentNote: 'NOIRAX speichert oder verarbeitet keine Kreditkartendaten. Alle Zahlungen werden sicher von Stripe abgewickelt.', dataLanguage: 'Spracheinstellung (lokal in Ihrem Browser gespeichert)', dataCookies: 'Cookie-Einwilligungspräferenz (lokal gespeichert)', purpose: 'Zweck der Datenverarbeitung', purposeText: 'Bereitstellung von Trading-Signal-Konten, Verarbeitung von Premium-Abonnements und Verbesserung des Dienstes. Wir verkaufen oder teilen keine persönlichen Daten mit Dritten.', retention: 'Datenspeicherung', retentionText: 'Kontodaten werden bis zur Löschungsanforderung aufbewahrt. Zahlungsaufzeichnungen werden gemäß den steuerrechtlichen Anforderungen aufbewahrt (in der Regel 5 Jahre).', rgpd: 'Ihre DSGVO-Rechte', rgpdText: 'Sie haben das Recht, auf Ihre personenbezogenen Daten zuzugreifen, sie zu berichtigen oder zu löschen, indem Sie uns kontaktieren.', contact: 'Kontakt', contactText: 'Für datenschutzbezogene Anfragen: aissaeljarrarielfahli@gmail.com' },
  common: { loading: 'Laden...', error: 'Fehler', retry: 'Wiederholen', close: 'Schließen', learnMore: 'Mehr erfahren', subscribe: 'Abonnieren', language: 'Sprache' },
  disclaimerBanner: { text: 'Bildungsinhalt. Keine Finanzberatung. Handel birgt Risiken.' },
  free: { title: 'Kostenlose Signale', subtitle: 'Echtzeit-Signale für die Top-15 Kryptos', delayWarning: 'Kostenlose Signale decken die Top 15 Coins mit konservativen Zielen ab.', exchangeDisclaimer: 'Diese Signale sind Bildungszwecke.', noSignals: 'Keine Signale verfügbar.', refreshIn: 'Aktualisierung in' },
  premium: { title: 'Premium Signale', subtitle: 'Volles Universum, optimierte Ziele, erweiterte Analyse', upgradePrompt: 'Schalten Sie das volle Potenzial frei', upgradeButton: 'Pläne ansehen', filters: 'Filter', allCoins: 'Alle Coins', confidence: 'Min. Vertrauen', timeframe: 'Zeitrahmen', positionCalculator: 'Rechner', capital: 'Kapital ($)', riskPercent: 'Risiko (%)', positionSize: 'Positionsgröße', riskLevel: 'Risikostufe', low: 'Niedrig', medium: 'Mittel', high: 'Hoch' },
  trackRecord: { title: 'Aufzeichnung', subtitle: 'Vollständige Signalhistorie.', winRate: 'Erfolgsrate', totalSignals: 'Signale gesamt', wins: 'Gewinne', losses: 'Verluste', pending: 'Ausstehend', noData: 'Keine Daten verfügbar.' },
  auth: { loginTitle: 'Anmelden', signupTitle: 'Konto Erstellen', email: 'E-Mail', password: 'Passwort', loginButton: 'Anmelden', signupButton: 'Registrieren', magicLink: 'Magic Link senden', noAccount: 'Kein Konto?', hasAccount: 'Bereits Konto?', error: 'Authentifizierungsfehler', success: 'Erfolgreich', checkEmail: 'Prüfen Sie Ihre E-Mail.', googleLogin: 'Mit Google fortfahren', googleSignup: 'Mit Google fortfahren', orContinue: 'oder' },
  premiumPrompt: { title: 'Premium Signal', description: 'Abonnieren Sie für die vollständige Analyse.', cta: 'Pläne ansehen', later: 'Später' },
  blog: { title: 'NOIRAX Blog', subtitle: 'Bildungsinhalt zur technischen Analyse.', readMore: 'Weiterlesen', noPosts: 'Noch keine Beiträge.', related: 'Verwandte Artikel' },
};

const it: Translations = {
  nav: { home: 'Home', free: 'Segnali Gratis', premium: 'Premium', trackRecord: 'Storico', pricing: 'Prezzi', login: 'Accedi', signup: 'Registrati', account: 'Mio Account', logout: 'Esci', blog: 'Blog' },
  home: { title: 'NOIRAX', subtitle: 'Sistema Autonomo di Segnali di Trading Crypto', terminalIntro: '> Sistema di analisi tecnica multi-valuta avviato', terminalAwaiting: '> In attesa dati di mercato...', latestSignals: 'Ultimi Segnali', ctaPremium: 'Sblocca Premium', ctaFree: 'Vedi Segnali Gratis', disclaimer: 'Contenuto educativo e informativo. Non è consulenza finanziaria.', typingText: 'Analisi di 100+ coppie in tempo reale' },
  legal: { title: 'Note Legali', disclaimer: 'NOIRAX è una piattaforma educativa di analisi tecnica crypto. Niente su questo sito costituisce consulenza finanziaria. Il trading crypto comporta alto rischio di perdita.', riskWarning: 'AVVERTENZA: Il trading crypto può comportare la perdita totale del capitale.', spainWarning: 'Avviso: Verificare la legalità del trading crypto nel proprio paese. Solo contenuto educativo.' },
  pricing: { title: 'Prezzi', free: { name: 'Gratis', price: 'Gratuito', description: 'Segnali in tempo reale per le principali crypto', features: ['Top 15 crypto', 'Aggiornamenti tempo reale', 'Obiettivi TP/SL conservativi', 'Analisi tecnica + fondamentale', 'Accesso pubblico'] }, premium: { name: 'Premium', price: '7,99€/mese', description: 'Universo completo con obiettivi ottimizzati', features: ['Universo completo (50+ crypto)', 'Scala TP1/TP2/TP3 ottimizzata', 'Obiettivi risk/reward estesi', 'Calcolatore posizione', 'Filtri storico avanzati', 'Spiegazioni IA prioritarie', 'Tag segnali fondamentali'], cta: 'Abbonati' }, annual: { name: 'Premium Annuale', price: '79€/anno', description: 'Risparmia 2 mesi', features: ['Tutto Premium', '2 mesi gratis'], cta: 'Abbonati' } },
  signal: { buySignal: 'Segnale ACQUISTO', sellSignal: 'Segnale VENDITA', entryZone: 'Zona d\'Ingresso', stopLoss: 'Stop Loss', takeProfit: 'Take Profit', riskReward: 'Rischio/Profitto', indicators: 'Indicatori', verified: 'Verificato', pending: 'In attesa', generated: 'Generato', confidenceLabel: 'Confluenza', confidenceTooltip: 'Accordo tra indicatori tecnici, non una probabilità di successo' },
  cookies: { text: 'Questo sito utilizza cookie solo per funzionalità essenziali. Nessun cookie di tracciamento viene utilizzato senza il tuo consenso.', accept: 'Accetta', reject: 'Rifiuta', moreInfo: 'Informativa sulla Privacy' },
  privacy: { title: 'Informativa sulla Privacy', dataController: 'Titolare del Trattamento', dataControllerText: 'NOIRAX (operato da NoiraMaster). Contatto: aissaeljarrarielfahli@gmail.com', dataCollected: 'Dati Raccolti', dataEmail: 'Indirizzo email (per creazione account e accesso)', dataPayment: 'Informazioni di pagamento', dataPaymentNote: 'NOIRAX non memorizza né elabora i dati delle carte di credito. Tutti i pagamenti sono gestiti in modo sicuro da Stripe.', dataLanguage: 'Preferenza linguistica (memorizzata localmente nel browser)', dataCookies: 'Preferenza di consenso ai cookie (memorizzata localmente)', purpose: 'Finalità del Trattamento', purposeText: 'Fornire account di segnali di trading, elaborare abbonamenti premium e migliorare il servizio. Non vendiamo né condividiamo dati personali con terze parti.', retention: 'Conservazione dei Dati', retentionText: 'I dati dell\'account vengono conservati fino alla richiesta di cancellazione. Le registrazioni di pagamento sono conservate come richiesto dalla legge fiscale (generalmente 5 anni).', rgpd: 'I Tuoi Diritti GDPR', rgpdText: 'Hai il diritto di accedere, rettificare o cancellare i tuoi dati personali in qualsiasi momento contattandoci.', contact: 'Contatto', contactText: 'Per richieste relative alla privacy: aissaeljarrarielfahli@gmail.com' },
  common: { loading: 'Caricamento...', error: 'Errore', retry: 'Riprova', close: 'Chiudi', learnMore: 'Scopri di più', subscribe: 'Abbonati', language: 'Lingua' },
  disclaimerBanner: { text: 'Contenuto educativo. Non un consiglio finanziario. Il trading comporta rischi.' },
  free: { title: 'Segnali Gratis', subtitle: 'Segnali in tempo reale per le principali crypto', delayWarning: 'I segnali gratuiti coprono le top 15 crypto con obiettivi conservativi.', exchangeDisclaimer: 'Questi segnali sono educativi.', noSignals: 'Nessun segnale disponibile.', refreshIn: 'Aggiorna tra' },
  premium: { title: 'Segnali Premium', subtitle: 'Universo completo, obiettivi ottimizzati, analisi avanzata', upgradePrompt: 'Sblocca tutto il potenziale', upgradeButton: 'Vedi Piani', filters: 'Filtri', allCoins: 'Tutte', confidence: 'Confidenza min', timeframe: 'Timeframe', positionCalculator: 'Calcolatore', capital: 'Capitale ($)', riskPercent: 'Rischio (%)', positionSize: 'Dimensione', riskLevel: 'Livello Rischio', low: 'Basso', medium: 'Medio', high: 'Alto' },
  trackRecord: { title: 'Storico', subtitle: 'Storico completo segnali.', winRate: 'Win Rate', totalSignals: 'Totale Segnali', wins: 'Vinte', losses: 'Perse', pending: 'In attesa', noData: 'Nessun dato disponibile.' },
  auth: { loginTitle: 'Accedi', signupTitle: 'Crea Account', email: 'Email', password: 'Password', loginButton: 'Accedi', signupButton: 'Registrati', magicLink: 'Invia Magic Link', noAccount: 'Non hai account?', hasAccount: 'Hai già account?', error: 'Errore autenticazione', success: 'Operazione riuscita', checkEmail: 'Controlla la tua email.', googleLogin: 'Continua con Google', googleSignup: 'Continua con Google', orContinue: 'oppure' },
  premiumPrompt: { title: 'Segnale Premium', description: 'Abbonati per vedere l\'analisi completa.', cta: 'Vedi Piani', later: 'Non ora' },
  blog: { title: 'Blog NOIRAX', subtitle: 'Contenuto educativo sull\'analisi tecnica.', readMore: 'Leggi altro', noPosts: 'Nessun articolo ancora.', related: 'Articoli Correlati' },
};

const ar: Translations = {
  nav: { home: 'الرئيسية', free: 'إشارات مجانية', premium: 'مميز', trackRecord: 'السجل', pricing: 'الأسعار', login: 'تسجيل الدخول', signup: 'إنشاء حساب', account: 'حسابي', logout: 'تسجيل الخروج', blog: 'المدونة' },
  home: { title: 'NOIRAX', subtitle: 'نظام إشارات تداول العملات الرقمية الآلي', terminalIntro: '> تم بدء نظام التحليل الفني متعدد العملات', terminalAwaiting: '> في انتظار بيانات السوق...', latestSignals: 'آخر الإشارات', ctaPremium: 'فتح المميز', ctaFree: 'عرض الإشارات المجانية', disclaimer: 'محتوى تعليمي وإعلامي. ليس نصيحة مالية.', typingText: 'تحليل أكثر من 100 زوج في الوقت الفعلي' },
  legal: { title: 'إشعار قانوني', disclaimer: 'NOIRAX هي منصة تعليمية وإعلامية للتحليل الفني للعملات الرقمية. لا شيء في هذا الموقع يشكل نصيحة مالية أو توصية استثمارية. تداول العملات الرقمية ينطوي على مخاطر عالية لخسارة مالية. لا نضمن أي ربحية. النتائج السابقة ليست مؤشراً على النتائج المستقبلية. يجب التحقق من قانونية تداول العملات الرقمية في بلدك قبل استخدام هذه المنصة.', riskWarning: 'تحذير المخاطر: تداول العملات الرقمية قد يؤدي إلى خسارة كاملة لرأس مالك المستثمر. تداول فقط بأموال يمكنك تحمل خسارتها.', spainWarning: 'تنبيه: يرجى التحقق من قانونية تداول العملات الرقمية في بلدك. بعض دول الأغلبية العربية تقيد أو تحظر تداول العملات الرقمية مؤسسياً. هذا المحتوى تعليمي فقط.' },
  pricing: { title: 'الأسعار', free: { name: 'مجاني', price: 'مجاناً', description: 'إشارات في الوقت الفعلي لأهم العملات', features: ['أفضل 15 عملة', 'تحديثات فورية', 'أهداف وقف/ربح محافظة', 'تحليل فني + أساسي', 'وصول عام'] }, premium: { name: 'مميز', price: '€7.99/شهر', description: 'جميع العملات مع أهداف محسنة', features: ['جميع العملات (50+)', 'سلم TP1/TP2/TP3 محسّن', 'أهداف مخاطرة/عائد موسعة', 'حاسبة حجم الصفقة', ' filtres سجل متقدمة', 'تحليل ذكاء اصطناعي أولوية', 'علامات إشارات أساسية'], cta: 'اشتراك' }, annual: { name: 'مميز سنوي', price: '€79/سنة', description: 'وفر شهرين', features: ['كل المميز', 'شهران مجاناً'], cta: 'اشتراك' } },
  signal: { buySignal: 'إشارة شراء', sellSignal: 'إشارة بيع', entryZone: 'منطقة الدخول', stopLoss: 'وقف الخسارة', takeProfit: 'جني الأرباح', riskReward: 'المخاطرة/العائد', indicators: 'المؤشرات المستخدمة', verified: 'تم التحقق', pending: 'قيد الانتظار', generated: 'تم التوليد', confidenceLabel: 'التوافق', confidenceTooltip: 'توافق بين المؤشرات الفنية، ليس احتمال نجاح' },
  cookies: { text: 'يستخدم هذا الموقع ملفات تعريف الارتباط للوظائف الأساسية فقط. لا يتم استخدام ملفات تعقب دون موافقتك.', accept: 'قبول', reject: 'رفض', moreInfo: 'سياسة الخصوصية' },
  privacy: { title: 'سياسة الخصوصية', dataController: 'المراقب', dataControllerText: 'NOIRAX (تديره NoiraMaster). اتصل: aissaeljarrarielfahli@gmail.com', dataCollected: 'البيانات التي تم جمعها', dataEmail: 'البريد الإلكتروني (لإنشاء الحساب وتسجيل الدخول)', dataPayment: 'معلومات الدفع', dataPaymentNote: 'NOIRAX لا تخزن أو تعالج بيانات بطاقات الائتمان. جميع المدفوعات تتم معالجتها بشكل آمن بواسطة Stripe.', dataLanguage: 'تفضيل اللغة (مخزن محلياً في متصفحك)', dataCookies: 'تفضيل الموافقة على ملفات تعريف الارتباط (مخزن محلياً)', purpose: 'الغرض من معالجة البيانات', purposeText: 'تقديم حسابات إشارات التداول ومعالجة الاشتراكات المميزة وتحسين الخدمة. نحن لا نبيع أو نشارك البيانات الشخصية مع أطراف ثالثة.', retention: 'الاحتفاظ بالبيانات', retentionText: 'يتم الاحتفاظ ببيانات الحساب حتى تطلب حذفها. يتم الاحتفاظ بسجلات الدفع وفقاً لمتطلبات القانون الضريبي (عادة 5 سنوات).', rgpd: 'حقوقك بموجب اللائحة العامة لحماية البيانات', rgpdText: 'لديك الحق في الوصول إلى بياناتك الشخصية أو تصحيحها أو حذفها في أي وقت عن طريق الاتصال بنا.', contact: 'اتصل بنا', contactText: 'للاستفسارات المتعلقة بالخصوصية: aissaeljarrarielfahli@gmail.com' },
  common: { loading: 'جارٍ التحميل...', error: 'خطأ', retry: 'إعادة المحاولة', close: 'إغلاق', learnMore: 'اعرف المزيد', subscribe: 'اشتراك', language: 'اللغة' },
  disclaimerBanner: { text: 'محتوى تعليمي. ليس نصيحة مالية. التداول ينطوي على مخاطر.' },
  free: { title: 'إشارات مجانية', subtitle: 'إشارات في الوقت الفعلي لأهم 15 عملة', delayWarning: 'الإشارات المجانية تغطي أفضل 15 عملة بأهداف محافظة.', exchangeDisclaimer: 'هذه الإشارات تعليمية.', noSignals: 'لا توجد إشارات متاحة حالياً.', refreshIn: 'تحديث في' },
  premium: { title: 'إشارات مميزة', subtitle: 'جميع العملات مع أهداف محسنة وتحليل متقدم', upgradePrompt: 'افتح الإمكانات الكاملة', upgradeButton: 'عرض الخطط', filters: 'تصفية', allCoins: 'جميع العملات', confidence: 'أقل ثقة', timeframe: 'الإطار الزمني', positionCalculator: 'حاسبة الصفقة', capital: 'رأس المال ($)', riskPercent: 'المخاطرة (%)', positionSize: 'حجم الصفقة', riskLevel: 'مستوى المخاطرة', low: 'منخفض', medium: 'متوسط', high: 'مرتفع' },
  trackRecord: { title: 'السجل', subtitle: 'سجل كامل للإشارات.', winRate: 'نسبة النجاح', totalSignals: 'إجمالي الإشارات', wins: 'ناجحة', losses: 'خاسرة', pending: 'معلقة', noData: 'لا توجد بيانات متاحة.' },
  auth: { loginTitle: 'تسجيل الدخول', signupTitle: 'إنشاء حساب', email: 'البريد الإلكتروني', password: 'كلمة المرور', loginButton: 'تسجيل الدخول', signupButton: 'إنشاء حساب', magicLink: 'إرسال رابط سحري', noAccount: 'ليس لديك حساب؟', hasAccount: 'لديك حساب بالفعل؟', error: 'خطأ في المصادقة', success: 'تمت العملية بنجاح', checkEmail: 'تحقق من بريدك الإلكتروني.', googleLogin: 'المتابعة مع Google', googleSignup: 'المتابعة مع Google', orContinue: 'أو' },
  premiumPrompt: { title: 'إشارة مميزة', description: 'اشترك لمشاهدة التحليل الكامل.', cta: 'عرض الخطط المميزة', later: 'ليس الآن' },
  blog: { title: 'مدونة NOIRAX', subtitle: 'محتوى تعليمي عن التحليل الفني.', readMore: 'اقرأ المزيد', noPosts: 'لا توجد مقالات بعد.', related: 'مقالات ذات صلة' },
};

const translations: Record<string, Translations> = { en, es, pt, fr, de, it, ar };

export function getLang(): string {
  if (typeof window === 'undefined') return 'en';
  const stored = localStorage.getItem('noirax_lang');
  if (stored && LOCALES.includes(stored as Locale)) return stored;
  const navLang = navigator.language.slice(0, 2);
  if (LOCALES.includes(navLang as Locale)) return navLang;
  return 'en';
}

export function setLang(lang: string): void {
  if (typeof window !== 'undefined') {
    localStorage.setItem('noirax_lang', lang);
  }
}

export function updateUserLang(supabase: any, userId: string, lang: string): void {
  if (supabase && userId) {
    supabase.from('users').update({ idioma_preferido: lang }).eq('id', userId).then(() => {});
  }
}

export function t(key: string, lang?: string): string {
  const currentLang = lang || getLang();
  const keys = key.split('.');
  const fallback = translations[currentLang] || translations['en'];
  let value: TranslationValue = fallback;
  for (const k of keys) {
    if (typeof value === 'object' && value !== null && k in value) {
      value = (value as { [key: string]: TranslationValue })[k];
    } else {
      value = translations['en'];
      for (const k2 of keys) {
        if (typeof value === 'object' && value !== null && k2 in value) {
          value = (value as { [key: string]: TranslationValue })[k2];
        } else {
          return key;
        }
      }
      break;
    }
  }
  if (Array.isArray(value)) return value.join(', ');
  return typeof value === 'string' ? value : key;
}

export function getAllLocales(): Locale[] {
  return [...LOCALES];
}
